# main menu navigation
menu:
  首页: /
  关于: /about
  归档: /archives

widgets:
  - tag
  - archive
  - recent_posts
  - category
  - profile

# social config
social:
  zhihu:
  twitter: /
  facebook: /
  linkedin:
  instagram: /
  github: heybigfish

user:
  name: heybigfish
  avatar: /images/avatar.jpg
  location: In the dust
  description: 永远年轻、永远热泪盈眶~
  footnotes: # footnotes

# documents: https://github.com/utterance/utterances
# API config: https://utteranc.es/
comment_utteranc:
  enable: true
  repo: heybigfish/Claudia-theme-blog # your blog repo

# documents: https://valine.js.org/quickstart.html
comment_valine:
  enable: false
  appId:
  appKey:

comment_disqus:
  enable: false
  url: # the url of your website main domain like this https://xxx.xxx/
  name: # the short name in disqus

# dark
# light
# user-can-set
appearance: auto # Default value is auto

# Miscellaneous
favicon: /images/favicon.png

# Google Analytics
ga_track_id:
ga_domain:

# Baidu Analytics
ba_track_id:

# picture of about page
about_pic: about.png
